apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: covidscreeningAPI
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: covidscreeningAPI
    spec:
      containers:
        - name: covidscreeningAPI
          image: covidscreeningregistry.azurecr.io/covidscreeningapi:v1
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
    name: covidscreeningAPI
spec:
  ports:
    - name: http-port
      port: 80
      targetPort: 80
  selector:
    app: covidscreeningAPI
  type: LoadBalancer